src/apps/idioma/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^idioma-listado/$', views.idioma_listado, name='idioma_listado'),
    url(r'^idioma-nivel-listado/$', views.idioma_nivel_listado, name='idioma_nivel_listado'),
    url(r'^idioma-ciclo-listado/$', views.idioma_ciclo_listado, name='idioma_ciclo_listado'),
    url(r'^idioma-ciclo-agregar/(?P<pk_idioma>\d+)/(?P<pk_nivel>\d+)/$', views.idioma_ciclo_crear, name='idioma_ciclo_crear'),
    url(r'^api-idioma-agregar/$', views.api_idioma_agregar, name='api_idioma_agregar'),
    url(r'^api-idioma-actualizar/$', views.api_idioma_actualizar, name='api_idioma_actualizar'),
    url(r'^api-nivel-idioma-agregar/$', views.api_nivel_idioma_agregar, name='api_nivel_idioma_agregar'),
    url(r'^api-nivel-idioma-actualizar/$', views.api_nivel_idioma_actualizar, name='api_nivel_idioma_actualizar'),
    # url(r'^registro/$', 'registro', name='registro'),

    # # RECUPERAR PASSWORD
    # url(r'^recuperar-password/$', 'recupera_password', name='recupera_password'),
    # url(r'^cambiar-password/(?P<uuid_hash>[-\w]+)$', 'set_password', name='set_password'),
    # url(r'^cambiar-password-ok/$', 'set_password_success', name='set_password_success'),

    # # PRIVATE VIEWS
    # url(r'^auth/$', 'logged_view', name='logged_view')
    # url(r'^login/$', 'home_prueba', name='ingresar'),
]

src/apps/matricula/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.inicio_matricula, name='inicio_matricula'),
    url(r'^matricula/(?P<pk>\d+)/$', views.matricular, name='matricular'),
    # url(r'^periodo_matricula/$', views.periodo_matricula, name='periodo_matricula'),
    url(r'^matricula-gracias/$', views.matricula_gracias, name='matricula_gracias'),
    url(r'^mi-matricula-listado/$', views.mi_matricula_listado, name='mi_matricula_listado'),
    url(r'^matricula-detalle/(?P<pk>\d+)/$', views.periodo_matricula_detalle, name='periodo_matricula_detalle'),
    url(r'^matricula-alumno-detalle/(?P<pk>\d+)/$', views.matricula_alumno_detalle, name='matricula_alumno_detalle'),
    url(r'^matricula-valida/(?P<pk>\d+)/$', views.matricula_valida, name='matricula_valida'),
    url(r'^api-validar-matricula/$', views.api_validar_matricula, name='api_validar_matricula'),
    url(r'^matricula-pdf/(?P<pk>\d+)/$', views.matricula_generar_pdf, name='matricula_generar_pdf'),
]

src/apps/programacion/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^aula-listado/$', views.aula_listado, name='aula_listado'),
    url(r'^aula-crear/$', views.aula_crear_modificar, name='aula_crear'),
    url(r'^turno-listado/$', views.turno_listado, name='turno_listado'),
    url(r'^horario-listado/$', views.horario_listado, name='horario_listado'),
    url(r'^horario-agregar/(?P<pk>\d+)/$', views.horario_crear_modificar, name='horario_crear'),
    url(r'^periodo-listado/$', views.periodo_listado, name='periodo_listado'),
    url(r'^programacion-listado/(?P<pk>\d+)/$', views.programacion_listado, name='programacion_listado'),
    url(r'^programacion-agregar/(?P<pk_periodo>\d+)/(?P<pk_idioma>\d+)/$', views.programacion_crear_modificar, name='programacion_crear_modificar'),
    url(r'^api-turno-agregar/$', views.api_turno_agregar, name='api_turno_agregar'),
    url(r'^api-turno-actualizar/$', views.api_turno_actualizar, name='api_turno_actualizar'),
]

src/apps/sistema/urls.py
from django.conf.urls import patterns, url
from . import views

urlpatterns = [
    url(r'^ingresar/$', views.login_view, name='login_view'),
    url(r'^bienvenido/$', views.bienvenido, name='bienvenido'),
    url(r'^salir/$', views.salir, name='salir'),
    # url(r'^registro/$', 'registro', name='registro'),

    # # RECUPERAR PASSWORD
    # url(r'^recuperar-password/$', 'recupera_password', name='recupera_password'),
    # url(r'^cambiar-password/(?P<uuid_hash>[-\w]+)$', 'set_password', name='set_password'),
    # url(r'^cambiar-password-ok/$', 'set_password_success', name='set_password_success'),

    # # PRIVATE VIEWS
    # url(r'^auth/$', 'logged_view', name='logged_view')
    # url(r'^login/$', 'home_prueba', name='ingresar'),
]

src/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT}),

    # WEB
    url(r'^sistema/', include('apps.sistema.urls', namespace="sistema")),
    url(r'^idioma/', include('apps.idioma.urls', namespace="idioma")),
    url(r'^programacion/', include('apps.programacion.urls', namespace="programacion")),
    url(r'', include('apps.alumno_profesor.urls', namespace="alumno_profesor")),
    url(r'', include('apps.matricula.urls', namespace="matricula")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'apps.web.views.page_404'
handler500 = 'apps.web.views.page_500'

src/apps/common/models.py
from django.db import models

# Create your models here.

src/apps/common/views.py
from django.shortcuts import render

# Create your views here.

src/templates/common/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Sistema</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <!-- Bootstrap 3.3.4 -->
    <link href="{{STATIC_URL}}bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <!-- Font Awesome Icons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <!-- Ionicons -->
    <link href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet" type="text/css" />

    <!-- Theme style -->
    <link href="{{STATIC_URL}}dist/css/AdminLTE.min.css" rel="stylesheet" type="text/css" />
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link href="{{STATIC_URL}}dist/css/skins/_all-skins.min.css" rel="stylesheet" type="text/css" />
    <link href="{{STATIC_URL}}css/daniel.css" rel="stylesheet" type="text/css" />

 {% block css %}

    {% endblock css %}
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

  </head>
<body class="sidebar-mini skin-blue">
<div class="wrapper">
{% include "common/header.html" %}
{% include "common/menu-nav.html" %}

    <div class="content-wrapper">
        <section class="content-header">
              <h3>
                {{titulo}} {% if subtitulo %}/<small>{{subtitulo}}</small>
                {% endif %}
              </h3>
            </section>
            <section class="content">
                {% block content %}

                {% endblock content %}
            </section>
        </div>
        {% include "common/footer.html" %}
    </div>

    <script src="{{STATIC_URL}}plugins/jQuery/jQuery-2.1.4.min.js"></script>
    <!-- jQuery UI 1.11.2 -->
    <script src="http://code.jquery.com/ui/1.11.2/jquery-ui.min.js" type="text/javascript"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
      $.widget.bridge('uibutton', $.ui.button);
    </script>
    <!-- Bootstrap 3.3.2 JS -->

    <script src="{{STATIC_URL}}bootstrap/js/bootstrap.min.js" type="text/javascript"></script>

    <script src="{{STATIC_URL}}plugins/sparkline/jquery.sparkline.min.js" type="text/javascript"></script>
    <!-- jvectormap -->
    <script src="{{STATIC_URL}}plugins/jvectormap/jquery-jvectormap-1.2.2.min.js" type="text/javascript"></script>
    <script src="{{STATIC_URL}}plugins/jvectormap/jquery-jvectormap-world-mill-en.js" type="text/javascript"></script>
    <!-- jQuery Knob Chart -->
    <script src="{{STATIC_URL}}plugins/knob/jquery.knob.js" type="text/javascript"></script>
    <!-- daterangepicker -->
    <!--<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.2/moment.min.js" type="text/javascript"></script>
    <script src="{{STATIC_URL}}plugins/daterangepicker/daterangepicker.js" type="text/javascript"></script> -->
     <!--datepicker -->
    <!--<script src="{{STATIC_URL}}plugins/datepicker/bootstrap-datepicker.js" type="text/javascript"></script>-->
    <!-- Bootstrap WYSIHTML5
    <script src="{{STATIC_URL}}plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js" type="text/javascript"></script>-->
    <!-- Slimscroll -->
    <!-- <script src="{{STATIC_URL}}plugins/slimScroll/jquery.slimscroll.min.js" type="text/javascript"></script> -->
    <!-- FastClick -->
    <!-- <script src='{{STATIC_URL}}plugins/fastclick/fastclick.min.js'></script> -->
    <!-- AdminLTE App -->

    <script src="{{STATIC_URL}}dist/js/app.min.js" type="text/javascript"></script>

    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <!-- <script src="{{STATIC_URL}}dist/js/pages/dashboard.js" type="text/javascript"></script>    -->

    {% block javascript %}

{% endblock javascript %}
</body>
</html>

src/templates/common/footer.html
  <footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>Version</b> 1
    </div>
    <strong>Copyright &copy; 2014-2015 </strong>
  </footer>

src/templates/common/header.html
      <header class="main-header">
        <!-- Logo -->
        <a href="#" class="logo color_white" target="_blank">
          <!-- mini logo for sidebar mini 50x50 pixels -->
          <span class="logo-mini"><b>A</b>LT</span>
          <!-- logo for regular state and mobile devices -->

      <!-- <span class="logo-lg"><img src="{{STATIC_URL}}img/logo-algodonera.png"></span> -->
          SISTEMA
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top" role="navigation">
          <!-- Sidebar toggle button-->
          <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
          </a>
          <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
              <!-- Messages: style can be found in dropdown.less-->
              <li class="dropdown user user-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <i class="glyphicon glyphicon-user"></i>
                  <span class="hidden-xs">{% if request.user.is_superuser %}
                    {{request.user.full_name}}
                  {% else %}
                    {{request.user.nombre}}
                  {% endif %}</span>
                </a>
                <ul class="dropdown-menu">
          <!-- User image -->
                  <li class="user-body">
                    <!--<img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image" />-->
                    <p>
                      {{request.user.email}} - USUARIO DEL SISTEMA
                      <small>Miembro desde {{request.user.last_login }}</small>
                    </p>
                  </li>
                  <!-- Menu Footer-->
                  <li class="user-footer">
                    <div class="pull-left">
                      <a href="#" class="btn btn-default btn-flat">Perfil</a>
                    </div>
                    <div class="pull-right">
                      <a href="{% url 'sistema:salir' %}" class="btn btn-default btn-flat">Salir</a>
                    </div>
                  </li>
                </ul>
              </li>
              <li>
              {% comment %}
                <a href="{% url 'auth:logout'%}" >SALIR</a>
              {% endcomment %}

              </li>
              <!-- Control Sidebar Toggle Button -->

            </ul>
          </div>
        </nav>
      </header>

src/templates/common/menu-nav.html
      <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
          <!-- Sidebar user panel -->
          <div class="user-panel solo_nombre">

            <div class="pull-left info position_left_cero">
              <p>{% if request.user.is_superuser %}
                Administrador
              {% else %}
                {{request.user.email}}
              {% endif %}</p>

              <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
          </div>
          <!-- search form -->
          <!--<form action="#" method="get" class="sidebar-form">
            <div class="input-group">
              <input type="text" name="q" class="form-control" placeholder="Search..."/>
              <span class="input-group-btn">
                <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
              </span>
            </div>
          </form>
           /.search form -->
          <!-- sidebar menu: : style can be found in sidebar.less -->
          <ul class="sidebar-menu">
            <li class="header">Menu Principal</li>
            {% if request.user.is_sistema %}

            <li class="treeview">
              <a href="#">
                <i class="glyphicon glyphicon-list-alt"></i> <span>Idioma</span> <i class="fa fa-angle-left pull-right"></i>
              </a>
              <ul class="treeview-menu">
                <li class="active"><a href="{% url 'idioma:idioma_listado' %}"><i class="fa fa-files-o"></i>Idioma</a>
                </li>
                <li><a href="{% url 'idioma:idioma_nivel_listado' %}"><i class="fa fa-files-o"></i>Nivel Idioma</a></li>
                <li><a href="{% url 'idioma:idioma_ciclo_listado'%}"><i class="fa fa-files-o"></i>Ciclo Idioma</a></li>

              </ul>
            </li>
            <li class="treeview">
              <a href="#">
                <i class="glyphicon glyphicon-list-alt"></i> <span>Programación</span> <i class="fa fa-angle-left pull-right"></i>
              </a>
              <ul class="treeview-menu">
                <li><a href="{% url 'programacion:turno_listado' %}"><i class="fa fa-user-plus"></i>Turno</a></li>
                <li class="active"><a href="{% url 'programacion:horario_listado' %}"><i class="fa fa-files-o"></i>Horario</a>
                </li>
                <li class="active"><a href="{% url 'programacion:aula_listado' %}"><i class="fa fa-files-o"></i>Aula</a>
                </li>
                <li class="active"><a href="{% url 'programacion:periodo_listado' %}"><i class="fa fa-files-o"></i>periodo para la programacion</a>
                </li>
              </ul>
            </li>
            <li class="treeview">
              <a href="#">
                <i class="glyphicon glyphicon-list-alt"></i> <span>Alumnos y Profesor</span> <i class="fa fa-angle-left pull-right"></i>
              </a>
              <ul class="treeview-menu">
                <li><a href="{% url 'alumno_profesor:profesor_listado' %}"><i class="fa fa-user-plus"></i>Listado Profesor</a></li>
                <li class="active"><a href="{% url 'alumno_profesor:alumno_listado' %}"><i class="fa fa-user-plus"></i></i>Listado Alumno</a>
                </li>
              </ul>
            </li>
            {% else %}
            <li class="treeview">
              <a href="#">
                <i class="glyphicon glyphicon-list-alt"></i> <span>Matricula</span> <i class="fa fa-angle-left pull-right"></i>
              </a>
              <ul class="treeview-menu">
                <li><a href="{% url 'matricula:inicio_matricula' %}"><i class="fa fa-files-o"></i>Ver Matricula Actual</a></li>
                <li class="active"><a href="{% url 'matricula:mi_matricula_listado' %}"><i class="fa fa-files-o"></i></i>Mis Matriculas</a>
                </li>
              </ul>
            </li>
            {% endif %}
          </ul>
        </section>
        <!-- /.sidebar -->
      </aside>