src/apps/idioma/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^idioma-listado/$', views.idioma_listado, name='idioma_listado'),
    url(r'^idioma-nivel-listado/$', views.idioma_nivel_listado, name='idioma_nivel_listado'),
    url(r'^idioma-ciclo-listado/$', views.idioma_ciclo_listado, name='idioma_ciclo_listado'),
    url(r'^idioma-ciclo-agregar/(?P<pk_idioma>\d+)/(?P<pk_nivel>\d+)/$', views.idioma_ciclo_crear, name='idioma_ciclo_crear'),
    url(r'^api-idioma-agregar/$', views.api_idioma_agregar, name='api_idioma_agregar'),
    url(r'^api-idioma-actualizar/$', views.api_idioma_actualizar, name='api_idioma_actualizar'),
    url(r'^api-nivel-idioma-agregar/$', views.api_nivel_idioma_agregar, name='api_nivel_idioma_agregar'),
    url(r'^api-nivel-idioma-actualizar/$', views.api_nivel_idioma_actualizar, name='api_nivel_idioma_actualizar'),
    # url(r'^registro/$', 'registro', name='registro'),

    # # RECUPERAR PASSWORD
    # url(r'^recuperar-password/$', 'recupera_password', name='recupera_password'),
    # url(r'^cambiar-password/(?P<uuid_hash>[-\w]+)$', 'set_password', name='set_password'),
    # url(r'^cambiar-password-ok/$', 'set_password_success', name='set_password_success'),

    # # PRIVATE VIEWS
    # url(r'^auth/$', 'logged_view', name='logged_view')
    # url(r'^login/$', 'home_prueba', name='ingresar'),
]

src/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT}),

    # WEB
    url(r'^sistema/', include('apps.sistema.urls', namespace="sistema")),
    url(r'^idioma/', include('apps.idioma.urls', namespace="idioma")),
    url(r'^programacion/', include('apps.programacion.urls', namespace="programacion")),
    url(r'', include('apps.alumno_profesor.urls', namespace="alumno_profesor")),
    url(r'', include('apps.matricula.urls', namespace="matricula")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'apps.web.views.page_404'
handler500 = 'apps.web.views.page_500'

src/apps/idioma/models.py
# -*- coding: utf-8 -*-
from django.db import models
from .constants import CHOICES_NIVEL, CHOICES_IDIOMAS


# Create your models here. #
class Idioma(models.Model):
    nombre = models.CharField("Nombre del idioma", max_length=120)

    class Meta:
        verbose_name = "Idioma"
        verbose_name_plural = "Idiomas"

    def __unicode__(self):
        return self.nombre


class NivelIdioma(models.Model):
    nombre = models.CharField("Nombre del Nivel idioma", max_length=120, choices=CHOICES_NIVEL)

    class Meta:
        verbose_name = "Nivel Idioma"
        verbose_name_plural = "Nivel Idiomas"

    def __unicode__(self):
        return self.nombre


class CicloIdioma(models.Model):
    nivel_idioma = models.ForeignKey(NivelIdioma, related_name='nivel_idioma_ciclo')
    idioma = models.ForeignKey(Idioma, related_name='idioma_ciclo_idioma')
    nombre = models.CharField("Nombre", max_length=120)

    class Meta:
        verbose_name = "CicloIdioma"
        verbose_name_plural = "CicloIdiomas"

    def __unicode__(self):
        return "%s - %s - %s" % (self.idioma, self.nivel_idioma, self.nombre)

src/apps/idioma/forms.py
from django import forms

src/apps/idioma/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.urlresolvers import reverse
from .models import Idioma, NivelIdioma, CicloIdioma
from django.forms.models import modelformset_factory
from apps.common.util import paginador_general
from django.db import connection
from django.http import JsonResponse
import json
# Create your views here.


def idioma_listado(request):
    idiomas = Idioma.objects.all().order_by("nombre")
    # cursor = connection.cursor()
    # cursor.execute("Select * From idioma_idioma")
    # for nue in cursor:
    #     print nue
    return render(request, "idioma/idioma_listado.html", locals())


def idioma_nivel_listado(request):
    nivel_idiomas = NivelIdioma.objects.all().order_by("nombre")
    return render(request, "idioma/idioma_nivel_listado.html", locals())


def idioma_ciclo_listado(request):
    query_idioma = request.GET.get("idioma_seleccionar")
    query_nivel = request.GET.get("nivel_seleccionar")
    ciclo_idiomas = CicloIdioma.objects.all().prefetch_related("idioma").prefetch_related("nivel_idioma").order_by("idioma__nombre")
    pagina = request.GET.get("pag", 1)
    pagina_cantidad = request.GET.get('pcantidad', 2)
    if query_idioma:
        ciclo_idiomas = ciclo_idiomas.filter(idioma=query_idioma)
    if query_nivel:
        ciclo_idiomas = ciclo_idiomas.filter(nivel_idioma=query_nivel)
    nivel_idiomas = NivelIdioma.objects.all().order_by("nombre")
    idiomas = Idioma.objects.all().order_by("nombre")
    ciclo_idiomas = paginador_general(ciclo_idiomas, pagina_cantidad, pagina)
    return render(request, 'idioma/idioma_ciclo_listado.html', locals())


def idioma_ciclo_crear(request, pk_idioma=False, pk_nivel=False):
    idioma = get_object_or_404(Idioma, pk=pk_idioma)
    nivel = get_object_or_404(NivelIdioma, pk=pk_nivel)
    nivel_idiomas = NivelIdioma.objects.all().order_by("nombre")
    NivelFormSet = modelformset_factory(CicloIdioma, extra=0, min_num=1, validate_min=True, can_delete=True, fields=('nombre', 'idioma', 'nivel_idioma', 'id'))
    if request.method == "POST":
        nivelFormSet = NivelFormSet(request.POST, queryset=CicloIdioma.objects.filter(nivel_idioma=pk_nivel, idioma=pk_idioma))
        if nivelFormSet.is_valid():
            nivelFormSet.save()
            return redirect(reverse("idioma:idioma_ciclo_listado"))
    else:
        nivelFormSet = NivelFormSet(queryset=CicloIdioma.objects.filter(nivel_idioma=pk_nivel, idioma=pk_idioma))
    return render(request, 'idioma/idioma_ciclo_crear.html', locals())


def api_idioma_agregar(request):

    if request.is_ajax():
        if request.method == "POST":
            listado_idioma = []
            for idioma in json.loads(request.POST.get("idioma")):
                if idioma:
                    guardado_idioma = Idioma(nombre=idioma)
                #     if idioma:
                #         listado_idioma.append(Idioma(nombre=idioma))
                # guardado_idioma = Idioma.objecdots.bulk_create(listado_idioma)
                    guardado_idioma.save()
                    listado = {}
                    listado['nombre'] = guardado_idioma.nombre
                    listado['id'] = guardado_idioma.id
                    listado_idioma.append(listado)
            data = {
                'listado': listado_idioma,
            }
    else:
        data = {"status": "error"}
    return JsonResponse(data)


def api_idioma_actualizar(request):

    if request.is_ajax():
        if request.method == "POST":
            guardado_idioma = Idioma.objects.get(id=request.POST.get("idioma_pk"))
            guardado_idioma.nombre = request.POST.get("idioma_nombre")
            guardado_idioma.save()
            data = {'status': 'ok'}
    else:
        data = {"status": "error"}
    return JsonResponse(data)


def api_nivel_idioma_agregar(request):

    if request.is_ajax():
        if request.method == "POST":
            listado_idioma = []
            for idioma in json.loads(request.POST.get("idioma")):
                guardado_nivel_idioma = NivelIdioma(nombre=idioma)
            #     if idioma:
            #         listado_idioma.append(Idioma(nombre=idioma))
            # guardado_nivel_idioma = Idioma.objecdots.bulk_create(listado_idioma)
                guardado_nivel_idioma.save()
                listado = {}
                listado['nombre'] = guardado_nivel_idioma.nombre
                listado['id'] = guardado_nivel_idioma.id
                listado_idioma.append(listado)
            data = {
                'listado': listado_idioma,
            }
    else:
        data = {"status": "error"}
    return JsonResponse(data)


def api_nivel_idioma_actualizar(request):

    if request.is_ajax():
        if request.method == "POST":
            guardado_nivel_idioma = NivelIdioma.objects.get(id=request.POST.get("idioma_pk"))
            guardado_nivel_idioma.nombre = request.POST.get("idioma_nombre")
            guardado_nivel_idioma.save()
            data = {'status': 'ok'}
    else:
        data = {"status": "error"}
    return JsonResponse(data)

src/templates/idioma/idioma_ciclo_crear.html
{% extends 'common/base.html' %}
{% block css %}
<link href="{{STATIC_URL}}plugins/iCheck/all.css" rel="stylesheet" type="text/css">
{% endblock css %}
{% block content %}

<div class="row">
  <div class="col-xs-12">
    <div class="box box-primary">
      <div class="box-header">
        <h3 class="box-title">
          Agregar el ciclo para el idioma <strong>{{idioma.nombre}}</strong> y nivel <strong>{{nivel.nombre}}</strong>
        </h3>

      </div>
      <div class="box-body">
      <form action="#" method="POST">
        {% csrf_token %}
        {{ nivelFormSet.management_form }}
        {% for nivel_idioma in nivelFormSet %}
            <div class="form-group form-nivel-idioma">
              <input type="hidden" {% if nivel_idioma.id.value %}value="{{nivel_idioma.id.value}}"{% endif %} name="{{nivel_idioma.id.html_name}}">
              <input type="hidden" class="permanecer-pk" value="{{idioma.pk}}" name="{{nivel_idioma.idioma.html_name}}">
              <input type="hidden" class="permanecer-pk" value="{{nivel.pk}}" name="{{nivel_idioma.nivel_idioma.html_name}}">
              <label for="">Nombre</label>
              <input type="text" name="{{nivel_idioma.nombre.html_name}}" {% if nivel_idioma.nombre.value %}value="{{nivel_idioma.nombre.value}}"{% endif %}>
              <label for="">Eliminar</label>
              <input type="checkbox" name="{{nivel_idioma.DELETE.html_name}}" class="flat-red">
            {{nivel_idioma.errors}}
            </div>
        {% endfor %}
        <button class="btn btn-success">Guardar</button>
      </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}
{% block javascript %}
<script src="{{STATIC_URL}}plugins/iCheck/icheck.min.js" type="text/javascript"></script>
<script src="{{STATIC_URL}}js/jquery_formset.js"></script>
<script>
    $(document).ready(function() {

        $('.form-nivel-idioma').formset({
            formCssClass: 'factura-form',
            prefix: "{{ nivelFormSet.prefix }}",
            deleteText: '',
            addText: 'Agregar',
            addCssClass: 'btn btn-success agregar-item',
            keepFieldValues: 'input.permanecer-pk'
        });
    });

</script>
{% endblock javascript %}

src/templates/idioma/idioma_ciclo_listado.html
{% extends 'common/base.html' %}
{% block content %}

<div class="row">
  <div class="col-xs-12">
    <div class="box box-primary">
      <div class="box-header">
        <h3 class="box-title">
            CICLO DE IDIOMAS
          </h3>
      </div>
        <div class="box-body">
            <div class="btn-group mb_20">
              <form action="#" method="GET">
              <select name="pcantidad" class="float-left" id="paginador">
                <option value="2" {% if pagina_cantidad == "2" %}selected{% endif %}>2</option>
                <option value="25" {% if pagina_cantidad == "25" %}selected{% endif %}>25</option>
                <option value="50" {% if pagina_cantidad == "50" %}selected{% endif %}>50</option>
                <option value="100" {% if pagina_cantidad == "100" %}selected{% endif %}>100</option>
              </select>
              <select name="idioma_seleccionar" id="select_idiomas">
                  <option value="">-------</option>
                {% for idioma in idiomas %}
                  <option value="{{idioma.pk}}" {% if query_idioma|lower == idioma.pk|lower %}selected{% endif %}>{{idioma.nombre}}</option>
                {% endfor %}
              </select>
              <select name="nivel_seleccionar" id="select_nivel">
                  <option value="">-------</option>
                {% for nivel in nivel_idiomas %}
                  <option value="{{nivel.pk}}" {% if query_nivel|lower == nivel.pk|lower %}selected{% endif %}>{{nivel.nombre}}</option>
                {% endfor %}
              </select>
                 <button id="filtros" class="btn btn-success btn-radius"><i class="fa fa-search"></i> Filtrar
                 </button>
                <a href="" id="link_agregar_ciclo" class="tooltip_agregar btn btn-success btn-radius"><i class="fa fa-edit "></i> Agregar/Modificar Ciclo
                  <span>Debe seleccionar el idioma y el nivel del idioma</span>
                </a>

              </form>
            </div>
            <div id="example1_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                <table id="example1" class="table table-bordered table-striped dataTable" role="grid" aria-describedby="example1_info">
                 <thead>
                  <tr>
                    <th>N°</th>
                    <th>Idioma</th>
                    <th>Nivel</th>
                    <th>Nombre</th>

                  </tr>
                </thead>
                  <tbody class="listado_idioma">
                  {% for ciclo in ciclo_idiomas %}
                    <tr role="row" class="odd row-fila" >
                      <td class="sorting_1">{{forloop.counter}}</td>
                      <td class="nombre_idioma"><h5>{{ciclo.idioma.nombre}}</h5><input type="hidden" data-pk="{{idioma.pk}}" class="input_modificar"></td>
                      <td class="nombre_idioma"><h5>{{ciclo.nivel_idioma}}</h5><input type="hidden" data-pk="{{ciclo.pk}}" class="input_modificar"></td>
                      <td class="nombre_idioma"><h5>{{ciclo.nombre}}</h5><input type="hidden" data-pk="{{ciclo.pk}}" class="input_modificar"></td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div id="listado_paginas">
              <ul>
                {% if ciclo_idiomas.has_previous %}
                <li id="anterior"><a href="" data-pagina="{{ciclo_idiomas.previous_page_number}}"><</a></li>
                {% endif %}
                {% for pagina_link in ciclo_idiomas.paginator.page_range %}
                <li><a href="?pag={{pagina_link}}" {% if pagina_link|lower == pagina|lower %}class="active"{% endif %} data-pagina="{{pagina_link}}">{{pagina_link}}</a></li>
                {% endfor %}
                {% if ciclo_idiomas.has_next %}
                <li id="siguiente"><a href="" data-pagina="{{ciclo_idiomas.next_page_number}}">></a></li>
                {% endif %}
              </ul>
            </div>
        </div>
    </div>
  </div>
</div>
{% endblock content %}
{% block javascript %}
  <script src="{{STATIC_URL}}js/common.js"></script>
  <script>
  $(document).ready(function() {
    $("#link_agregar_ciclo").mouseover(function(event) {
      /* Act on the event */
      var select_idiomas = $("#select_idiomas").val();
      var select_nivel = $("#select_nivel").val();
      if (select_nivel=="" || select_idiomas=="") {
        $(this).find('span').addClass('aparecer-alerta')
      }
    });
    $("#link_agregar_ciclo").click(function(event) {
      /* Act on the event */
      event.preventDefault()
      var url = "/idioma/idioma-ciclo-agregar/";
      var select_idiomas = $("#select_idiomas").val();
      var select_nivel = $("#select_nivel").val();
      if (select_nivel=="" || select_idiomas=="") {
        $(this).find('span').addClass('aparecer-alerta')
      }
      else{
        window.location.href = url + select_idiomas + "/" + select_nivel;
      }
    });
    $("#listado_paginas a").click(function(event) {
      /* Act on the event */
      event.preventDefault();
      window.location.search=paginar($(this).attr('data-pagina'), {{pagina}})
    });
  });
  </script>
{% endblock javascript %}

src/templates/idioma/idioma_listado.html
{% extends 'common/base.html' %}

{% block css %}
<link href="{{STATIC_URL}}plugins/datatables/dataTables.bootstrap.css" rel="stylesheet" type="text/css">
{% endblock css %}
{% block content %}

<div class="row">
  <div class="col-xs-12">
   <div class="box box-primary">
    <div class="actualizo_correctamente alert alert-success">
        Se actualizo correctamente el idioma
    </div>
    <div class="box-header">
        <h3 class="box-title">
            IDIOMAS
        </h3>
    </div>
    <div class="box-body">
      <form action="#" method="POST" id="form_idioma">
        <div class="btn-group mb_20">
            <a href="" id="agregar_idioma" class="btn btn-success btn-radius">Agregar Idioma</a>
            <button type="button" id="guardar_crear_idioma" class="btn btn-success btn-radius"><i class="fa fa-fw fa-save"></i> Guardar</button>
        </div>
        <div class="cnt-formulario">
        </div>
      </form>

      <div id="example1_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
            <table id="example1" class="table table-bordered table-striped dataTable" role="grid" aria-describedby="example1_info">
             <thead>
              <tr>
                <th>N°</th>
                <th>Nombres</th>
                <th>Modficar / Guardar</th>
              </tr>
            </thead>
              <tbody class="listado_idioma">
              {% for idioma in idiomas %}
                <tr role="row" class="odd row-fila" >
                  <td class="sorting_1">{{forloop.counter}}</td>
                  <td class="nombre_idioma"><h5>{{idioma.nombre}}</h5><input type="hidden" data-pk="{{idioma.pk}}" class="input_modificar"></td>
                  <td><button type="button" class="btn btn-primary modficar_idioma">Modificar</button><button type="button" class="btn btn-success guardar_idioma guardar_none">Guardar</button>
                  </td>
                </tr>
               {% endfor %}
              </tbody>
              </table>
      </div>
    </div><!-- /.box-body -->
  </div>
</div>

{% endblock content %}
{% block javascript %}

<!-- FastClick -->

    <!-- DATA TABES SCRIPT -->

    <!-- SlimScroll -->
    <script src="{{STATIC_URL}}plugins/slimScroll/jquery.slimscroll.min.js" type="text/javascript"></script>
    <!-- FastClick -->

    <script src='{{STATIC_URL}}js/jquery_formset.js'></script>
    <script src='{{STATIC_URL}}js/cookies.js'></script>
    <script src='{{STATIC_URL}}js/api.js'></script>
    <!-- AdminLTE App -->

    <script type="text/javascript">

      $(document).ready(function() {
        $("body").on('click', '#agregar_idioma', function(event) {
            /* Act on the event */
            event.preventDefault()
            var contador_formulario = $(".formulario_inicial").length + 1
            html = '<div class="formulario_inicial form-group"><label for="">Nombre del Idioma </label> <input type="text" class="idioma_nombre" name="idioma"></div>'
            $(".cnt-formulario").append(html)

        });
        $("body").on('click', '.guardar_idioma  ', function(event) {

            var padre_fila = $(this).closest('.row-fila')
            var pk = padre_fila.find('.input_modificar').attr('data-pk');
            var texto = padre_fila.find('.input_modificar').val()
            url_idioma_actualizar = '{% url "idioma:api_idioma_actualizar" %}'
            /* Act on the event */
            ajax_actualizar_idioma(padre_fila, texto, pk, url_idioma_actualizar)
        });
        $("#guardar_crear_idioma").click(function(event) {
        /* Act on the event */
            var arreglo_idiomas = new Array()
            var contador_listado = $(".listado_idioma tr").length
            var url_idioma_crear = '{% url "idioma:api_idioma_agregar" %}'
            $(".idioma_nombre").each(function(index, el) {
                arreglo_idiomas.push($(this).val())
            });

            ajax_crear_idioma(arreglo_idiomas, url_idioma_crear, contador_listado)
        });
        $("body").on('click', '.modficar_idioma', function(event) {
        /* Act on the event */
            event.preventDefault()
            var padre_fila = $(this).closest('.row-fila')
            var texto = padre_fila.find('.nombre_idioma h5').text()
            padre_fila.find('.input_modificar').val(texto);
            padre_fila.find('.input_modificar').attr('type', 'text');
            padre_fila.find('.nombre_idioma h5').text("")
            padre_fila.find('.guardar_idioma').removeClass('guardar_none').addClass('guardar_block')
            padre_fila.find('.modficar_idioma').addClass('guardar_none')
        });
      });
    </script>
{% endblock javascript %}

src/templates/idioma/idioma_nivel_listado.html
{% extends 'common/base.html' %}

{% block css %}
<link href="{{STATIC_URL}}plugins/datatables/dataTables.bootstrap.css" rel="stylesheet" type="text/css">
{% endblock css %}
{% block content %}

<div class="row">
  <div class="col-xs-12">
   <div class="box box-primary">
    <div class="actualizo_correctamente alert alert-success">
        Se actualizo correctamente el nivel idioma
    </div>
      <div class="box-header">
        <h3 class="box-title">
            NIVEL IDIOMAS
        </h3>
    </div>
    <div class="box-body">
      <form action="#" method="POST" id="form_idioma">
        <div class="btn-group mb_20">
            <a href="" id="agregar_idioma" class="btn btn-success btn-radius">Agregar Nivel Idioma</a>
            <button type="button" id="guardar_crear_idioma" class="btn btn-success btn-radius"><i class="fa fa-fw fa-save"></i> Guardar</button>
        </div>
        <div class="cnt-formulario">
        </div>
      </form>
      <div id="example1_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
            <table id="example1" class="table table-bordered table-striped dataTable" role="grid" aria-describedby="example1_info">
             <thead>
              <tr>
                <th>N°</th>
                <th>Nombres</th>
                <th>Modficar / Guardar</th>
              </tr>
            </thead>
              <tbody class="listado_idioma">
              {% for idioma in nivel_idiomas %}
                <tr role="row" class="odd row-fila" >
                  <td class="sorting_1">{{forloop.counter}}</td>
                  <td class="nombre_idioma"><h5>{{idioma.nombre}}</h5><input type="hidden" data-pk="{{idioma.pk}}" class="input_modificar"></td>
                  <td><button type="button" class="btn btn-primary modficar_idioma">Modificar</button><button type="button" class="btn btn-success guardar_idioma guardar_none">Guardar</button>
                  </td>
                </tr>
               {% endfor %}
              </tbody>
              </table>
      </div>


    </div><!-- /.box-body -->
  </div>
</div>

{% endblock content %}
{% block javascript %}

<!-- FastClick -->

    <!-- DATA TABES SCRIPT -->

    <!-- SlimScroll -->
    <script src="{{STATIC_URL}}plugins/slimScroll/jquery.slimscroll.min.js" type="text/javascript"></script>
    <!-- FastClick -->

    <script src='{{STATIC_URL}}js/jquery_formset.js'></script>
    <script src='{{STATIC_URL}}js/cookies.js'></script>
    <script src='{{STATIC_URL}}js/api.js'></script>
    <!-- AdminLTE App -->

    <script type="text/javascript">

      $(document).ready(function() {
        $("body").on('click', '#agregar_idioma', function(event) {
            /* Act on the event */
            event.preventDefault()
            var contador_formulario = $(".formulario_inicial").length + 1
            html = '<div class="formulario_inicial form-group"><label for="">Nombre del Nivel Idioma </label> <input type="text" class="idioma_nombre" name="idioma"></div>'
            $(".cnt-formulario").append(html)

        });
        $("body").on('click', '.guardar_idioma  ', function(event) {
            event.preventDefault();
            console.log("entro")
            var padre_fila = $(this).closest('.row-fila')
            var pk = padre_fila.find('.input_modificar').attr('data-pk');
            var texto = padre_fila.find('.input_modificar').val()
            url_idioma_actualizar = '{% url "idioma:api_nivel_idioma_actualizar" %}'
            /* Act on the event */
            ajax_actualizar_idioma(padre_fila, texto, pk, url_idioma_actualizar)
        });
        $("#guardar_crear_idioma").click(function(event) {
        /* Act on the event */
            var arreglo_idiomas = new Array()
            var contador_listado = $(".listado_idioma tr").length
            var url_idioma_crear = '{% url "idioma:api_nivel_idioma_agregar" %}'
            $(".idioma_nombre").each(function(index, el) {
                arreglo_idiomas.push($(this).val())
            });
            ajax_crear_idioma(arreglo_idiomas, url_idioma_crear, contador_listado)
        });
        $("body").on('click', '.modficar_idioma', function(event) {
        /* Act on the event */
            event.preventDefault()
            var padre_fila = $(this).closest('.row-fila')
            var texto = padre_fila.find('.nombre_idioma h5').text()
            padre_fila.find('.input_modificar').val(texto);
            padre_fila.find('.input_modificar').attr('type', 'text');
            padre_fila.find('.nombre_idioma h5').text("")
            padre_fila.find('.guardar_idioma').removeClass('guardar_none').addClass('guardar_block')
            padre_fila.find('.modficar_idioma').addClass('guardar_none')
        });
      });
    </script>
{% endblock javascript %}