src/apps/alumno_profesor/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^profesor-listado/$', views.profesor_listado, name='profesor_listado'),
    url(r'^profesor-crear/$', views.profesor_crear_modificar, name='profesor_crear'),
    url(r'^profesor-modificar/(?P<pk>\d+)/$', views.profesor_crear_modificar, name='profesor_modificar'),
    url(r'^alumno-listado/$', views.alumno_listado, name='alumno_listado'),
    url(r'^alumno-detalle/(?P<pk>\d+)/$', views.alumno_detalle, name='alumno_detalle'),
    url(r'^alumno-registrar/$', views.alumno_crear_modificar, name='alumno_crear'),
]

src/apps/matricula/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.inicio_matricula, name='inicio_matricula'),
    url(r'^matricula/(?P<pk>\d+)/$', views.matricular, name='matricular'),
    # url(r'^periodo_matricula/$', views.periodo_matricula, name='periodo_matricula'),
    url(r'^matricula-gracias/$', views.matricula_gracias, name='matricula_gracias'),
    url(r'^mi-matricula-listado/$', views.mi_matricula_listado, name='mi_matricula_listado'),
    url(r'^matricula-detalle/(?P<pk>\d+)/$', views.periodo_matricula_detalle, name='periodo_matricula_detalle'),
    url(r'^matricula-alumno-detalle/(?P<pk>\d+)/$', views.matricula_alumno_detalle, name='matricula_alumno_detalle'),
    url(r'^matricula-valida/(?P<pk>\d+)/$', views.matricula_valida, name='matricula_valida'),
    url(r'^api-validar-matricula/$', views.api_validar_matricula, name='api_validar_matricula'),
    url(r'^matricula-pdf/(?P<pk>\d+)/$', views.matricula_generar_pdf, name='matricula_generar_pdf'),
]

src/apps/sistema/urls.py
from django.conf.urls import patterns, url
from . import views

urlpatterns = [
    url(r'^ingresar/$', views.login_view, name='login_view'),
    url(r'^bienvenido/$', views.bienvenido, name='bienvenido'),
    url(r'^salir/$', views.salir, name='salir'),
    # url(r'^registro/$', 'registro', name='registro'),

    # # RECUPERAR PASSWORD
    # url(r'^recuperar-password/$', 'recupera_password', name='recupera_password'),
    # url(r'^cambiar-password/(?P<uuid_hash>[-\w]+)$', 'set_password', name='set_password'),
    # url(r'^cambiar-password-ok/$', 'set_password_success', name='set_password_success'),

    # # PRIVATE VIEWS
    # url(r'^auth/$', 'logged_view', name='logged_view')
    # url(r'^login/$', 'home_prueba', name='ingresar'),
]

src/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT}),

    # WEB
    url(r'^sistema/', include('apps.sistema.urls', namespace="sistema")),
    url(r'^idioma/', include('apps.idioma.urls', namespace="idioma")),
    url(r'^programacion/', include('apps.programacion.urls', namespace="programacion")),
    url(r'', include('apps.alumno_profesor.urls', namespace="alumno_profesor")),
    url(r'', include('apps.matricula.urls', namespace="matricula")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'apps.web.views.page_404'
handler500 = 'apps.web.views.page_500'

src/apps/sistema/models.py
# -*- coding: utf-8 -*-

from pbkdf2 import crypt
from logging import getLogger
from uuid import uuid4
import re

from django.conf import settings
from django.db import models

log = getLogger('django')

SECRET_KEY = settings.AUTH_SECRET_KEY
SALT = ''.join(re.findall("[a-zA-Z0-9]+", SECRET_KEY))
NUMERO_DE_ITERACIONES = 500


class Usuario(models.Model):
    is_active = models.BooleanField('¿Activo?', default=True, blank=True)
    last_login = models.DateTimeField('Último Login', blank=True, null=True)
    email = models.EmailField('Email', blank=True)
    password = models.CharField('Contraseña', max_length=255, default='',
        blank=True)

    set_password = models.BooleanField('¿Contraseña encriptada?', default=False)
    uuid_hash = models.CharField('UUID', max_length=36, default='', blank=True,
        help_text='Aleautorio utilizado para recuperar la contraseña')

    def __unicode__(self):
        return unicode(self.password)

    class Meta:
        verbose_name = u'Administrador Usuario'
        verbose_name_plural = u'Administrador Usuarios'

    def save(self, *args, **kwargs):
        if not self.uuid_hash:
            self.uuid_hash = str(uuid4())

        if not self.set_password:
            self.password = encrypt_password(self.password)
            self.set_password = True

        super(Usuario, self).save(*args, **kwargs)

    def is_password_valid(self, password):
        return validad_password(password, self.password)

    def is_authenticated(self):
        return True

    @property
    def is_sistema(self):
        return True

    @property
    def is_staff(self):
        return False


# HELPERS
def encrypt_password(password):
    ''' Encripta la contraseña '''
    return crypt(password, SALT, NUMERO_DE_ITERACIONES)


def validad_password(password, encoded):
    ''' Contrasta la contraseña brindada con el valor encriptado '''
    return encrypt_password(password) == encoded

src/apps/sistema/forms.py
# -*- coding: utf-8 -*-
from logging import getLogger

from django import forms
from django.contrib.auth import authenticate
from django.contrib.sites.models import Site
from django.core.mail import EmailMessage
from django.core.urlresolvers import reverse
from django.template import Context
from django.template.loader import get_template
from django.conf import settings

from .models import Usuario

log = getLogger('django')


class LoginForm(forms.Form):
    ''' Formulario de acceso al sistema '''
    username = forms.EmailField(label='Email')
    username.widget.attrs.update({'autofocus': 'true', 'tabindex': '1'})
    password = forms.CharField(label='Contraseña', min_length=6,
        max_length=32, widget=forms.PasswordInput)
    password.widget.attrs.update({'tabindex': '2'})

    # def clean_username(self):
    #     username = self.cleaned_data['username']
    #     try:
    #         Usuario.objects.get(email=username)
    #     except Usuario.DoesNotExist:
    #         mensaje = u'El email no ha sido registrado'
    #         raise forms.ValidationError(mensaje)

    #     return username

    def auth(self):
        cd = self.cleaned_data
        return authenticate(username=cd['username'], password=cd['password'])


class RegistroForm(forms.Form):
    ''' Formulario de Registro '''
    username = forms.EmailField(label='Email')
    password = forms.CharField(label='Contraseña', min_length=7,
        max_length=32, widget=forms.PasswordInput)

    def clean_username(self):
        username = self.cleaned_data['username']
        try:
            Usuario.objects.get(email=username)
            mensaje = (u'El email ya ha sido registrado. <br>Puede ingresar' +
                u'desde <a class="ingresar" href={0}>aquí</a>'.format(
                    reverse('auth:login')))
            raise forms.ValidationError(mensaje)
        except Usuario.DoesNotExist:
            return username

    def save(self):
        cd = self.cleaned_data
        Usuario(email=cd['username'], password=cd['password']).save()

    def auth(self):
        cd = self.cleaned_data
        return authenticate(username=cd['username'], password=cd['password'])


class RecuperaPasswordForm(forms.Form):
    '''
        Formulario que solicita el email para iniciar el proceso de
        recuperación de contraseña.
    '''
    username = forms.EmailField(label='Email')

    def clean_username(self):
        username = self.cleaned_data['username']

        try:
            self.u = Usuario.objects.get(email=username)
        except Usuario.DoesNotExist:
            mensaje = 'El email no ha sido registrado'
            raise forms.ValidationError(mensaje)

        return username

    def enviaEmail(self):
        htmly = get_template('auth/password/email-setpassword.html')
        site = Site.objects.get(id=settings.SITE_ID)
        cd = self.cleaned_data
        cd['SITE'] = site.domain
        cd['STATIC_URL'] = site.domain + '/' + settings.STATIC_URL
        cd['usuario'] = self.u
        d = Context(cd)

        html_content = htmly.render(d)
        asunto = u'Actualización de Contraseña'
        mail = '{0}<{1}>'.format(settings.PROJECT_NAME,
            settings.DEFAULT_FROM_EMAIL)
        msg = EmailMessage(asunto, html_content, mail, [self.u.email])
        msg.content_subtype = "html"
        msg.send()


class SetPasswordForm(forms.Form):
    uuid_hash = forms.CharField(label='', widget=forms.HiddenInput)
    email = forms.EmailField(label='Email')
    email.widget.attrs.update({'readonly': 'readonly'})
    password = forms.CharField(label='Nueva contraseña', min_length=7,
        max_length=32, widget=forms.PasswordInput)

    def clean_email(self):
        uuid_hash = self.cleaned_data['uuid_hash']
        email = self.cleaned_data['email']
        try:
            self.u = Usuario.objects.get(email=email, uuid_hash=uuid_hash)
        except Usuario.DoesNotExist:
            raise forms.ValidationError('El email o la clave temporal son' +
                'incorrectos!')

        return email

    def save(self):
        cd = self.cleaned_data
        usuario = self.u
        usuario.set_password = False
        usuario.uuid_hash = ''
        usuario.password = cd['password']
        usuario.save()

    def enviaEmail(self):
        htmly = get_template('auth/password/email-password-update.html')
        site = Site.objects.get(id=settings.SITE_ID)
        cd = self.cleaned_data
        cd['SITE'] = site.domain
        cd['STATIC_URL'] = site.domain + '/' + settings.STATIC_URL
        cd['usuario'] = self.u
        d = Context(cd)

        html_content = htmly.render(d)
        asunto = u'Actualización de Contraseña'
        mail = '{0}<{1}>'.format(settings.PROJECT_NAME,
            settings.DEFAULT_FROM_EMAIL)
        msg = EmailMessage(asunto, html_content, mail, [self.u.email])
        msg.content_subtype = "html"
        msg.send()

src/apps/sistema/views.py
# -*- coding: utf-8 -*-
# SQL #
from django.db import connection
from logging import getLogger
from django.utils import timezone
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import logout_then_login
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.template import RequestContext as ctx

from .forms import (LoginForm,)
from .models import Usuario

log = getLogger('django')


def bienvenido(request):
    prueba = "texdasdsato"

    return render(request, 'sistema/bienvenido.html', locals())


# def registro(request):
#     log.info('VIEW: registro')

#     if request.user.is_authenticated():
#         return redirect(reverse('auth:logged_view'))

#     if request.method == 'POST':
#         form = RegistroForm(request.POST)

#         if form.is_valid():
#             form.save()
#             user = form.auth()
#             login(request, user)

#             return redirect(reverse('auth:logged_view'))
#         else:
#             log.warning('Error de formulario')
#     else:
#         form = RegistroForm()

#     return render('auth/registro.html', locals(),
#         context_instance=ctx(request))


def login_view(request):
    log.info('VIEW: login_view')
    # query_usuario = Usuario.objects.raw("Select * From sistema_usuario where id = %s", [1])
    # for query in query_usuario:
    #     print "--------------"
    #     print query.email
    #     print query.password
    # if request.user.is_authenticated():
    #     return redirect(reverse('sistema:logged_view'))
    # cursor = connection.cursor()
    # cursor.execute("Select * From sistema_usuario")
    # print cursor.fechone()
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            user = form.auth()
            if user is not None:
                if user.is_active:
                    user.last_login = timezone.now()
                    user.save()
                    login(request, user)
                    return redirect(reverse('sistema:bienvenido'))
                else:
                    messages.add_message(request, messages.WARNING,
                        'El usuario no se encuentra activo')
            else:
                messages.add_message(request, messages.WARNING,
                        u'El email y contraseña son inválidos')
        else:
            log.warning('Error de formulario')
    else:
        form = LoginForm()

    return render(request, 'sistema/login.html', locals())


def salir(request):
    return logout_then_login(request, reverse('sistema:login_view'))


# def set_password(request, uuid_hash):
#     log.info('VIEW: set_password')

#     if request.method == 'POST':
#         form = SetPasswordForm(request.POST)
#         if form.is_valid():
#             form.save()
#             form.enviaEmail()
#             return HttpResponseRedirect(
#                 reverse('auth:set_password_success'))
#         else:
#             log.warning('Error de formulario')
#     else:
#         try:
#             user = Usuario.objects.get(uuid_hash=uuid_hash)
#         except Usuario.DoesNotExist():
#             user = None
#         form = SetPasswordForm(initial={'email': user.email,
#             'uuid_hash': uuid_hash})

#     return render('auth/password/set-password.html', locals(),
#         context_instance=ctx(request))


# def set_password_success(request):
#     '''
#         Pantalla mostrada al cambiar la contraseña satisfactoriamente.
#         Redirecciona al Login y muestra un mensaje.
#     '''
#     log.info('VIEW: set_password_success')

#     return redirect(reverse('auth:login') + '?up=1')


# def recupera_password(request):
#     log.info('VIEW: recupera_passowrd')

#     if request.method == 'POST':
#         form = RecuperaPasswordForm(request.POST)
#         if form.is_valid():
#             form.enviaEmail()
#             messages.add_message(request, messages.INFO,
#                         'Se le ha enviado un email con las instrucciones a'
#                         ' seguir')
#         else:
#             log.warning('Error de formulario')
#     else:
#         form = RecuperaPasswordForm()

#     return render('auth/password/recupera-password.html', locals(),
#         context_instance=ctx(request))


# # PRIVATE VIEW
# @login_required(login_url=reverse_lazy('auth:login'))
# def logged_view(request):
#     log.info('VIEW: logged_view')

#     return render('auth/privado.html', locals(),
#         context_instance=ctx(request))

src/templates/sistema/bienvenido.html
{% extends 'common/base.html' %}
{% block content %}

<div class="row">
  <div class="col-xs-12">
    <div class="box box-primary">
      <div class="box-header">
        <h3 class="box-title">
        	Bienvenido al administrador de Sistema.
        </h3>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

src/templates/sistema/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Sistema de Matricula</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.5 -->
    <link rel="stylesheet" href="{{STATIC_URL}}bootstrap/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{STATIC_URL}}dist/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="{{STATIC_URL}}dist/css/skins/_all-skins.min.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link href="{{STATIC_URL}}css/daniel.css" rel="stylesheet" type="text/css" />

  </head>
  <!-- ADD THE CLASS layout-top-nav TO REMOVE THE SIDEBAR. -->
  <body class="hold-transition skin-blue layout-top-nav">
    <div class="wrapper">

      <header class="main-header">
        <nav class="navbar navbar-static-top">
          <div class="container">
            <div class="navbar-header">
              <a href="{% url 'matricula:inicio_matricula' %}" class="navbar-brand">SISTEMA DE MATRICULA</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->

            <!-- Navbar Right Menu -->
              <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                  <!-- Messages: style can be found in dropdown.less-->

                  <!-- Notifications Menu -->

                  <!-- Tasks Menu -->

                  <!-- User Account Menu -->
                  {% if not request.user.is_authenticated %}

                  <li class="">
                    <!-- Menu Toggle Button -->
                    <a href="{% url 'sistema:login_view' %}" >             <!-- The user image in the navbar-->

                      <strong class="hidden-xs">Ingresar</strong>
                    </a>

                  </li>
                  <li class="">
                    <!-- Menu Toggle Button -->
                    <a href="{% url 'alumno_profesor:alumno_crear' %}" >             <!-- The user image in the navbar-->

                      <strong class="hidden-xs">Registrar</strong>
                    </a>

                  </li>
                  {% else %}

                    <li class="">
                    <!-- Menu Toggle Button -->
                      <a href="{% url 'sistema:bienvenido' %}" >             <!-- The user image in the navbar-->

                        <strong class="hidden-xs">{{request.user.email}}</strong>
                      </a>

                    </li>
                    <li class="">
                    <!-- Menu Toggle Button -->
                    <a href="{% url 'sistema:salir' %}" class="hidden-xs">
                    <strong class="hidden-xs">Salir</strong>
                    </a>          <!-- The user image in the navbar-->



                  </li>
                  {% endif %}
                </ul>
              </div><!-- /.navbar-custom-menu -->
          </div><!-- /.container-fluid -->
        </nav>
      </header>
      <!-- Full Width Column -->
      <div class="content-wrapper">
        <div class="container">
          <!-- Content Header (Page header) -->
          <section class="content-header mb_20">
            <h3>
              MATRICULA del {{periodos.0.fecha_inicio}} - {{periodos.0.fecha_final}}
            </h3>
          </section>

          <!-- Main content -->
          <section class="content" style="background:white;">
            <div id="example1_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                <table id="example1" class="table table-bordered table-striped dataTable" role="grid" aria-describedby="example1_info">
                 <thead>
                  <tr>
                    <th>N°</th>
                    <th>Ciclo idioma</th>
                    <th>Profesor</th>
                    <th>Aula</th>
                    <th>Horario</th>
                  </tr>
                </thead>
                  <tbody class="listado_idioma">
                  {% for programa in periodos.0.periodo_programacion.all %}
                    <tr role="row" class="odd row-fila" >
                      <td class="sorting_1">{{forloop.counter}}</td>
                      <td class="nombre_idioma"><a href="{{programa.get_absolute_url}}"><h5>{{programa.ciclo_idioma}}</h5></a></td>
                      <td class="nombre_idioma"><h5>{{programa.profesor}}</h5></td>
                      <td class="nombre_idioma"><h5>{{programa.aula.numero_aula}}</h5></td>
                      <td class="nombre_idioma"><h5>{{programa.horario}}</h5></td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
          </section><!-- /.content -->
        </div><!-- /.container -->
      </div><!-- /.content-wrapper -->
      <footer class="main-footer">
        <div class="container">
          <div class="pull-right hidden-xs">
            <b>Version</b> 1
          </div>
          <strong>Proyecto realizado por estudiantes de la FIIS.</strong>
        </div><!-- /.container -->
      </footer>
    </div><!-- ./wrapper -->

    <!-- jQuery 2.1.4 -->
    <script src="{{STATIC_URL}}plugins/jQuery/jQuery-2.1.4.min.js"></script>
    <!-- Bootstrap 3.3.5 -->
    <script src="{{STATIC_URL}}bootstrap/js/bootstrap.min.js"></script>
    <!-- SlimScroll -->
    <script src="{{STATIC_URL}}plugins/slimScroll/jquery.slimscroll.min.js"></script>
    <!-- FastClick -->
    <script src="{{STATIC_URL}}plugins/fastclick/fastclick.min.js"></script>
    <!-- AdminLTE App -->
    <script src="{{STATIC_URL}}dist/js/app.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{{STATIC_URL}}dist/js/demo.js"></script>
  </body>
</html>

src/templates/sistema/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Sistema de miembros</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <!-- Bootstrap 3.3.4 -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
    <!-- Font Awesome Icons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <!-- Theme style -->
    <link href="{% static 'dist/css/AdminLTE.min.css' %}" rel="stylesheet" type="text/css" />
    <!-- iCheck -->
    <link href="{% static 'plugins/iCheck/square/blue.css' %}" rel="stylesheet" type="text/css" />
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body class="login-page">
    <div class="login-box">
      <!--<div class="login-logo">
        <a href="http://eulogio.webfactional.com/" class="login_logo" target="_blank">
        <img src="{{STATIC_URL}}img/logo-algodonera.png">
        </a>
      </div> /.login-logo -->
      <div class="login-box-body">
        <p class="login-box-msg">Iniciar Sesión</p>
        <form action="#" method="post" autocomplete="off">
          {% csrf_token %}
          <div class="form-group has-feedback">
            <input type="text" autocomplete="off" name="{{form.username.html_name}}" value="" class="form-control" placeholder="Usuario"/>
            <span class="glyphicon glyphicon glyphicon-user form-control-feedback"></span>
            <p class="input_errores">{{form.username.errors.as_text}}</p>
          </div>
          <div class="form-group has-feedback">
            <input type="password" autocomplete="off" name="{{form.password.html_name}}" class="form-control" placeholder="Password"/>
            <span class="glyphicon glyphicon-lock form-control-feedback"></span>
            <p class="input_errores">{{form.password.errors.as_text}}</p>
          </div>
          <div class="row">
            <div class="col-xs-8">

            </div><!-- /.col -->
            <div class="col-xs-4">
              <button type="submit" class="btn btn-primary btn-block btn-flat">Ingresar</button>
            </div><!-- /.col -->
          </div>
          {% if messages %}
          <ul class="messages">
              {% for message in messages %}
              <li{% if message.tags %} class="{{ message.tags }} input_errores"{% endif %}>{{ message }}</li>
              {% endfor %}
          </ul>
          {% endif %}
        </form>


        <a href="{% url 'alumno_profesor:alumno_crear' %}">Registrar</a><br>


      </div><!-- /.login-box-body -->
    </div><!-- /.login-box -->

    <!-- jQuery 2.1.4 -->
    <script src="{% static 'plugins/jQuery/jQuery-2.1.4.min.js' %}"></script>
    <!-- Bootstrap 3.3.2 JS -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}" type="text/javascript"></script>
    <!-- iCheck -->
    <script src="{% static 'plugins/iCheck/icheck.min.js' %}" type="text/javascript"></script>
    <script>
      $(function () {
        $('input').iCheck({
          checkboxClass: 'icheckbox_square-blue',
          radioClass: 'iradio_square-blue',
          increaseArea: '20%' // optional
        });
      });
    </script>
  </body>
</html>