src/apps/idioma/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^idioma-listado/$', views.idioma_listado, name='idioma_listado'),
    url(r'^idioma-nivel-listado/$', views.idioma_nivel_listado, name='idioma_nivel_listado'),
    url(r'^idioma-ciclo-listado/$', views.idioma_ciclo_listado, name='idioma_ciclo_listado'),
    url(r'^idioma-ciclo-agregar/(?P<pk_idioma>\d+)/(?P<pk_nivel>\d+)/$', views.idioma_ciclo_crear, name='idioma_ciclo_crear'),
    url(r'^api-idioma-agregar/$', views.api_idioma_agregar, name='api_idioma_agregar'),
    url(r'^api-idioma-actualizar/$', views.api_idioma_actualizar, name='api_idioma_actualizar'),
    url(r'^api-nivel-idioma-agregar/$', views.api_nivel_idioma_agregar, name='api_nivel_idioma_agregar'),
    url(r'^api-nivel-idioma-actualizar/$', views.api_nivel_idioma_actualizar, name='api_nivel_idioma_actualizar'),
    # url(r'^registro/$', 'registro', name='registro'),

    # # RECUPERAR PASSWORD
    # url(r'^recuperar-password/$', 'recupera_password', name='recupera_password'),
    # url(r'^cambiar-password/(?P<uuid_hash>[-\w]+)$', 'set_password', name='set_password'),
    # url(r'^cambiar-password-ok/$', 'set_password_success', name='set_password_success'),

    # # PRIVATE VIEWS
    # url(r'^auth/$', 'logged_view', name='logged_view')
    # url(r'^login/$', 'home_prueba', name='ingresar'),
]

src/apps/programacion/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^aula-listado/$', views.aula_listado, name='aula_listado'),
    url(r'^aula-crear/$', views.aula_crear_modificar, name='aula_crear'),
    url(r'^turno-listado/$', views.turno_listado, name='turno_listado'),
    url(r'^horario-listado/$', views.horario_listado, name='horario_listado'),
    url(r'^horario-agregar/(?P<pk>\d+)/$', views.horario_crear_modificar, name='horario_crear'),
    url(r'^periodo-listado/$', views.periodo_listado, name='periodo_listado'),
    url(r'^programacion-listado/(?P<pk>\d+)/$', views.programacion_listado, name='programacion_listado'),
    url(r'^programacion-agregar/(?P<pk_periodo>\d+)/(?P<pk_idioma>\d+)/$', views.programacion_crear_modificar, name='programacion_crear_modificar'),
    url(r'^api-turno-agregar/$', views.api_turno_agregar, name='api_turno_agregar'),
    url(r'^api-turno-actualizar/$', views.api_turno_actualizar, name='api_turno_actualizar'),
]

src/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT}),

    # WEB
    url(r'^sistema/', include('apps.sistema.urls', namespace="sistema")),
    url(r'^idioma/', include('apps.idioma.urls', namespace="idioma")),
    url(r'^programacion/', include('apps.programacion.urls', namespace="programacion")),
    url(r'', include('apps.alumno_profesor.urls', namespace="alumno_profesor")),
    url(r'', include('apps.matricula.urls', namespace="matricula")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'apps.web.views.page_404'
handler500 = 'apps.web.views.page_500'

src/apps/programacion/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.core.urlresolvers import reverse
from apps.alumno_profesor.models import Profesor
from apps.idioma.models import CicloIdioma
# # Create your models here.


class Turno(models.Model):
    nombre = models.CharField("Turno", max_length=60)

    class Meta:
        verbose_name = "Turno"
        verbose_name_plural = "Turnos"

    def __unicode__(self):
        return self.nombre


class Horario(models.Model):
    turno = models.ForeignKey(Turno, related_name='turno_horario')
    hora = models.TimeField("Horario Inicio")
    hora_fin = models.TimeField("Horario FIn")

    class Meta:
        verbose_name = "Horario"
        verbose_name_plural = "Horarios"

    def __unicode__(self):
        return '%s: %s - %s' % (self.turno, self.hora, self.hora_fin)


class Aula(models.Model):
    numero_aula = models.IntegerField("Numero de aula", unique=True)
    capacidad = models.IntegerField("capacidad", blank=True)

    class Meta:
        verbose_name = "Aula"
        verbose_name_plural = "Aulas"

    def __unicode__(self):
        return "%s - %s" % (self.numero_aula, self.capacidad)


class Periodo(models.Model):
    fecha_inicio = models.DateField("Fecha inicio")
    fecha_final = models.DateField("Fecha final")

    class Meta:
        verbose_name = "Fecha"
        verbose_name_plural = "Fechas"

    def get_absolute_url(self):
        return reverse('programacion:programacion_listado', kwargs={'pk': self.pk})

    def __unicode__(self):
        return "%s - %s" % (self.fecha_inicio, self.fecha_final)


class Programacion(models.Model):
    aula = models.ForeignKey(Aula, related_name='aula_programacion')
    periodo = models.ForeignKey(Periodo, related_name='periodo_programacion')
    ciclo_idioma = models.ForeignKey(CicloIdioma, related_name='ciclo_idioma_programacion')
    profesor = models.ForeignKey(Profesor, related_name='profesor_programacion')
    horario = models.ForeignKey(Horario, related_name='horario_programacion')

    class Meta:
        verbose_name = "Programacion"
        verbose_name_plural = "Programacions"

    def get_absolute_url(self):
        return reverse('matricula:matricular', kwargs={'pk': self.pk})

    def get_matricula_detalle_url(self):
        return reverse('matricula:periodo_matricula_detalle', kwargs={'pk': self.pk})

    def __str__(self):
        return str(self.ciclo_idioma)

src/apps/programacion/forms.py
from django import forms
from .models import Periodo, Programacion


class PeriodoForm(forms.ModelForm):
    class Meta:
        model = Periodo
        fields = ('fecha_inicio', 'fecha_final',)


class ProgramacionForm(forms.ModelForm):
    class Meta:
        model = Programacion
        fields = ('aula', 'periodo', 'ciclo_idioma', 'profesor', 'horario')

src/apps/programacion/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.core.urlresolvers import reverse
from django.db import connection
from django.forms.models import modelformset_factory
from apps.common.util import paginador_general
from apps.idioma.models import Idioma, CicloIdioma
from apps.alumno_profesor.models import Profesor
from .models import Turno, Horario, Aula, Programacion, Periodo
from django.http import JsonResponse
from .forms import PeriodoForm, ProgramacionForm
import json
import datetime
# Create your views here.


def turno_listado(request):
    turnos = Turno.objects.all().order_by('nombre')
    return render(request, 'programacion/turno_listado.html', locals())


def horario_listado(request):
    turnos = Turno.objects.all().order_by('nombre')
    horarios = Horario.objects.all().prefetch_related("turno")
    pagina = request.GET.get("pag", 1)
    pagina_cantidad = request.GET.get('pcantidad', 25)
    query_turno = request.GET.get("horario_seleccionar", False)
    if query_turno:
        horarios = horarios.filter(turno__pk=query_turno)
    horarios = paginador_general(horarios, pagina_cantidad, pagina)
    return render(request, 'programacion/horario_listado.html', locals())


def horario_crear_modificar(request, pk=False):
    turno = get_object_or_404(Turno, pk=pk)
    HorarioFormSet = modelformset_factory(Horario, extra=0, min_num=1, validate_min=True, can_delete=True, fields=('hora', 'hora_fin', 'id', 'turno'))
    if request.method == "POST":
        horarioFormSet = HorarioFormSet(request.POST, queryset=Horario.objects.filter(turno__pk=pk))
        if horarioFormSet.is_valid():
            horarioFormSet.save()
            return redirect(reverse("programacion:horario_listado"))
    else:
        horarioFormSet = HorarioFormSet(queryset=Horario.objects.filter(turno__pk=pk))
    return render(request, 'programacion/horario_crear_modificar.html', locals())


def aula_listado(request):
    cursor = connection.cursor()
    aulas = cursor.execute("Select * From programacion_aula")

    return render(request, 'programacion/aula_listado.html', locals())


def periodo_listado(request):
    periodos = Periodo.objects.all().order_by("-fecha_final")
    pagina = request.GET.get("pag", 1)
    pagina_cantidad = request.GET.get('pcantidad', 50)
    query_fecha_inicio = request.GET.get("fecha_inicio", "")
    query_fecha_final = request.GET.get("fecha_final", "")
    if query_fecha_inicio:
        query_fecha_inicio = datetime.datetime.strptime(query_fecha_inicio, "%d-%m-%Y").date()
        periodos = periodos.filter(fecha_inicio__gte=query_fecha_inicio)
    if query_fecha_final:
        query_fecha_final = datetime.datetime.strptime(query_fecha_final, "%d-%m-%Y").date()
        periodos = periodos.filter(fecha_inicio__lte=query_fecha_final)
    if request.method == "POST":
        fecha_inicio = request.POST.get("form_fecha_inicio")
        fecha_final = request.POST.get("form_fecha_final")
        fecha_inicio = datetime.datetime.strptime(fecha_inicio, "%d-%m-%Y").date()
        fecha_final = datetime.datetime.strptime(fecha_final, "%d-%m-%Y").date()
        Periodo(fecha_final=fecha_final, fecha_inicio=fecha_inicio).save()
        return redirect(reverse("programacion:periodo_listado"))
    else:
        ejecuto_post = False
    periodos = paginador_general(periodos, pagina_cantidad, pagina)
    return render(request, 'programacion/periodo_listado.html', locals())


def programacion_listado(request, pk=False):
    periodo = get_object_or_404(Periodo, pk=pk)
    idiomas = Idioma.objects.all()
    programacion = Programacion.objects.filter(periodo=periodo).prefetch_related('aula').prefetch_related('horario__turno').prefetch_related('profesor').prefetch_related('ciclo_idioma__idioma').prefetch_related('ciclo_idioma__nivel_idioma')
    pagina = request.GET.get("pag", 1)
    pagina_cantidad = request.GET.get('pcantidad', 25)
    query_idioma = request.GET.get("query_idioma", False)
    if query_idioma:
        programacion = programacion.filter(ciclo_idioma__idioma=query_idioma)
    programacion = paginador_general(programacion, pagina_cantidad, pagina)
    return render(request, 'programacion/programacion_listado.html', locals())


def programacion_crear_modificar(request, pk_idioma=False, pk_periodo=False):
    periodo = get_object_or_404(Periodo, pk=pk_periodo)
    aulas = Aula.objects.all()
    profesores = Profesor.objects.all()
    horarios = Horario.objects.all()
    ciclo_idiomas = CicloIdioma.objects.filter(idioma=pk_idioma)
    if request.method == "POST":
        form = ProgramacionForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse("programacion:programacion_listado", kwargs={'pk': pk_periodo}))
    else:
        form = ProgramacionForm()
    return render(request, 'programacion/programacion_crear_modificar.html', locals())


def aula_crear_modificar(request, pk_idioma=False):
    AulaFormSet = modelformset_factory(Aula, extra=1, min_num=1, validate_min=True, fields=('capacidad', 'numero_aula', 'id'))
    if request.method == "POST":
        aulaFormSet = AulaFormSet(request.POST, queryset=Aula.objects.all())
        if aulaFormSet.is_valid():
            aulaFormSet.save()
            return redirect(reverse("programacion:aula_listado"))
    else:
        aulaFormSet = AulaFormSet(queryset=Aula.objects.all())
    return render(request, 'programacion/aula_crear_modificar.html', locals())


def api_turno_agregar(request):

    if request.is_ajax():
        if request.method == "POST":
            listado_turno = []
            print request.POST.get("Turno")
            for turno in json.loads(request.POST.get("turno")):
                if turno:
                    guardado_turno = Turno(nombre=turno)
                #     if idioma:
                #         listado_turno.append(Idioma(nombre=idioma))
                # guardado_turno = Idioma.objecdots.bulk_create(listado_turno)
                    guardado_turno.save()
                    listado = {}
                    listado['nombre'] = guardado_turno.nombre
                    listado['id'] = guardado_turno.id
                    listado_turno.append(listado)
            data = {
                'listado': listado_turno,
            }
    else:
        data = {"status": "error"}
    return JsonResponse(data)


def api_turno_actualizar(request):

    if request.is_ajax():
        if request.method == "POST":
            guardar_turno = Turno.objects.get(id=request.POST.get("turno_pk"))
            guardar_turno.nombre = request.POST.get("turno_nombre")
            guardar_turno.save()
            data = {'status': 'ok'}
    else:
        data = {"status": "error"}
    return JsonResponse(data)

src/templates/programacion/aula_listado.html
{% extends 'common/base.html' %}
{% block content %}

<div class="row">
  <div class="col-xs-12">
    <div class="box box-primary">
        <div class="box-header">
          <h3 class="box-title">
            Aulas
          </h3>
        </div>
        <div class="box-body">
            <div class="btn-group mb_20">
                <a href="{% url 'programacion:aula_crear' %}" class="btn btn-success">Agregar Aula</a>

            </div>
            <div id="example1_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                <table id="example1" class="table table-bordered table-striped dataTable" role="grid" aria-describedby="example1_info">
                 <thead>
                  <tr>
                    <th>N°</th>
                    <th>Aula</th>
                    <th>Capacidad</th>
                  </tr>
                </thead>
                  <tbody class="listado_idioma">
                  {% for aula in aulas %}
                    <tr role="row" class="odd row-fila" >
                      <td class="sorting_1">{{forloop.counter}}</td>
                      <td class="nombre_idioma"><h5>{{aula.1}}</h5><input type="hidden" data-pk="{{idioma.pk}}" class="input_modificar"></td>
                      <td class="nombre_idioma"><h5>{{aula.2}} personas</h5><input type="hidden" data-pk="{{aula.0}}" class="input_modificar"></td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
  </div>
</div>
{% endblock content %}

src/templates/programacion/periodo_listado.html
{% extends 'common/base.html' %}
{% block css %}
<link href="{{STATIC_URL}}css/jquery.datetimepicker.css" rel="stylesheet" type="text/css" />

{% endblock css %}
{% block content %}

<div class="row">
  <div class="col-xs-12">
    <div class="box box-primary">
      <div class="box-header">
        <h3 class="box-title">
            Periodo de la Programacion
        </h3>
      </div>
      <div class="box-body">
        <div class="box-body">
            <div class="btn-group mb_20">
                <form action="#" class="mb_20" method="GET">
                    <select name="pcantidad" class="float-left" id="paginador">
                        <option value="25" {% if pagina_cantidad == "25" %}selected{% endif %}>25</option>
                        <option value="50" {% if pagina_cantidad == "50" %}selected{% endif %}>50</option>
                        <option value="100" {% if pagina_cantidad == "100" %}selected{% endif %}>100</option>
                    </select>
                    <label for="">RANGOS</label>
                    <input type="text" class="datetimepicker" name="fecha_inicio" {% if query_fecha_inicio %}value="{{query_fecha_inicio|date:"d-m-Y"}}"{% endif %}>
                    <input type="text" class="datetimepicker" name="fecha_final" {% if query_fecha_final %}value="{{query_fecha_final|date:"d-m-Y"}}"{% endif %}>
                    <button id="filtros" class="btn btn-success btn-radius"><i class="fa fa-search"></i> Filtrar
                     </button>
                    {% if not ejecuto_post %}
                    <a href="" id="link_agregar_periodo" class="tooltip_agregar btn btn-success btn-radius"><i class="fa fa-edit "></i> Agregar/Modificar Periodo
                    </a>
                    {% endif %}

              </form>
               <form action="#" method="POST" id="form-periodo">
                <div class="form-group ingresar_periodo {% if not ejecuto_post %}guardar_none{% endif %}">
                    {% csrf_token %}
                    <label for="id_fecha_inicio">Fecha inicio:</label>
                    <input class="datetimepicker" id="id_fecha_inicio" name="form_fecha_inicio" type="text">
                    <label for="id_fecha_final">Fecha final:</label>
                    <input class="datetimepicker" id="id_fecha_final" name="form_fecha_final" type="text">
                    <p>Campos Obligatorios</p>
                    {{form.errors}}
                    <button class="btn btn-success guardar_periodo"><i class="fa fa-fw fa-save"></i>Guardar</button>
                </div>
               </form>
            </div>
            <div id="example1_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                <table id="example1" class="table table-bordered table-striped dataTable" role="grid" aria-describedby="example1_info">
                 <thead>
                  <tr>
                    <th>N°</th>
                    <th>Fecha Inicio</th>
                    <th>Fecha Final</th>
                    <th>Modificar</th>
                  </tr>
                </thead>
                  <tbody class="listado_idioma">
                  {% for periodo in periodos %}
                    <tr role="row" class="odd row-fila" >
                      <td class="sorting_1">{{forloop.counter}}</td>
                      <td class="nombre_fecha_inicio"><h5><a href="{{periodo.get_absolute_url}}">{{periodo.fecha_inicio}}</a></h5><input type="hidden" data-pk="{{periodo.pk}}" class="datetimepicker input_modificar_inicio"></td>
                      <td class="nombre_fecha_final"><h5>{{periodo.fecha_final}}</h5><input type="hidden" data-pk="{{periodo.pk}}" class="datetimepicker input_modificar_final"></td>
                      <td><button type="button" class="btn btn-primary modficar_idioma">Modificar</button><button type="button" class="btn btn-success guardar_idioma guardar_none">Guardar</button>
                      </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div id="listado_paginas">
              <ul>
                {% if periodos.has_previous %}
                <li id="anterior"><a href="" data-pagina="{{periodos.previous_page_number}}"><</a></li>
                {% endif %}
                {% for pagina_link in periodos.paginator.page_range %}
                <li><a href="?pag={{pagina_link}}" {% if pagina_link|lower == pagina|lower %}class="active"{% endif %} data-pagina="{{pagina_link}}">{{pagina_link}}</a></li>
                {% endfor %}
                {% if periodos.has_next %}
                <li id="siguiente"><a href="" data-pagina="{{periodos.next_page_number}}">></a></li>
                {% endif %}
              </ul>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}
{% block javascript %}
<script src="{{STATIC_URL}}js/common.js"></script>
<script src="{{STATIC_URL}}js/jquery.datetimepicker.js"></script>
<script>
    $(document).ready(function() {
        $("body").on('click', '.guardar_idioma  ', function(event) {
            event.preventDefault();
            var padre_fila = $(this).closest('.row-fila')
            var pk = padre_fila.find('.input_modificar').attr('data-pk');
            var texto = padre_fila.find('.input_modificar').val()
            url_idioma_actualizar = '{% url "idioma:api_nivel_idioma_actualizar" %}'
            /* Act on the event */
            ajax_actualizar_idioma(padre_fila, texto, pk, url_idioma_actualizar)
        });
        $("body").on('click', '.modficar_idioma', function(event) {
        /* Act on the event */
            event.preventDefault()
            var padre_fila = $(this).closest('.row-fila')
            var fecha_inicio = padre_fila.find('.nombre_fecha_inicio h5').text()
            padre_fila.find('.input_modificar_inicio').val(fecha_inicio);
            padre_fila.find('.input_modificar_inicio').attr('type', 'text');
            padre_fila.find('.nombre_fecha_inicio h5').text("")
            var fecha_final = padre_fila.find('.nombre_fecha_final h5').text()
            padre_fila.find('.input_modificar_final').val(fecha_final);
            padre_fila.find('.input_modificar_final').attr('type', 'text');
            padre_fila.find('.nombre_fecha_final h5').text("")
            padre_fila.find('.guardar_idioma').removeClass('guardar_none').addClass('guardar_block')
            padre_fila.find('.modficar_idioma').addClass('guardar_none')
        });
        $("#listado_paginas a").click(function(event) {
      /* Act on the event */
            event.preventDefault();
            window.location.search=paginar($(this).attr('data-pagina'), {{pagina}})
        });
        $(".guardar_periodo").click(function(event) {
          /* Act on the event */
          event.preventDefault();
          var fecha_inicial = $("#id_fecha_inicio").val()
          var fecha_final = $("#id_fecha_final").val()
          if (fecha_inicial != "" && fecha_final != "") {
              $("#form-periodo").submit();
          };

        });
        $("#link_agregar_periodo").click(function(event) {
      /* Act on the event */
          event.preventDefault()
          $(this).addClass('guardar_none')
          $(".ingresar_periodo").removeClass('guardar_none')
        });
        $('.datetimepicker').datetimepicker({
          timepicker: false,
		      format:'d-m-Y',
        });
        // $('.datetimepicker_start').datetimepicker({
        //   format:'d-m-Y',
        //   onShow:function( ct ){
        //    this.setOptions({
        //     maxDate:jQuery('.datetimepicker_start').val()?jQuery('.datetimepicker_end').val():false
        //    })
        //   },
        //   timepicker:false
        //  });
        //  $('.datetimepicker_end').datetimepicker({
        //   format:'d-m-Y',
        //   onShow:function( ct ){
        //    this.setOptions({
        //     minDate:jQuery('.datetimepicker_start').val()?jQuery('.datetimepicker_end').val():false
        //    })
        //   },
        //   timepicker:false
        //  });
    });
</script>
{% endblock javascript %}

src/templates/programacion/turno_listado.html
{% extends 'common/base.html' %}
{% block content %}

<div class="row">
  <div class="col-xs-12">
    <div class="box box-primary">
        <div class="actualizo_correctamente alert alert-success">
            Se actualizo correctamente el Turno
        </div>
        <div class="box-header">
          <h3 class="box-title">
            Turno
          </h3>
        </div>
        <div class="box-body">
            <form action="#" method="POST" id="form_turno">
                <div class="btn-group mb_20">
                    <a href="" id="agregar_turno" class="btn margin-right-20 btn-success btn-radius">Agregar Turno</a>
                    <button type="button" id="guardar_crear_turno" class="btn btn-success btn-radius"><i class="fa fa-fw fa-save"></i> Guardar</button>
                </div>
                <div class="cnt-formulario">
                </div>
            </form>
            <div id="example1_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                <table id="example1" class="table table-bordered table-striped dataTable" role="grid" aria-describedby="example1_info">
                 <thead>
                  <tr>
                    <th>N°</th>
                    <th>Turno</th>
                    <th>Modificar</th>
                  </tr>
                </thead>
                  <tbody class="listado_idioma">
                  {% for turno in turnos %}
                    <tr role="row" class="odd row-fila" >
                      <td class="sorting_1">{{forloop.counter}}</td>
                      <td class="nombre_turno"><h5>{{turno.nombre}}</h5><input type="hidden" data-pk="{{turno.pk}}" class="input_modificar"></td>
                      <td><button type="button" class="btn btn-primary modificar_turno">Modificar</button><button type="button" class="btn btn-success actualizar_turno guardar_none">Guardar</button>
                      </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
  </div>
</div>
{% endblock content %}
{% block javascript %}
<script src='{{STATIC_URL}}js/cookies.js'></script>
<script src='{{STATIC_URL}}js/api.js'></script>
<!-- AdminLTE App -->

<script type="text/javascript">
    $(document).ready(function() {
        $("body").on('click', '#agregar_turno', function(event) {
            /* Act on the event */
            event.preventDefault()
            console.log("entro")
            var contador_formulario = $(".formulario_inicial").length + 1
            html = '<div class="formulario_inicial form-group"><label for="">Nombre del Turno </label> <input type="text" class="turno_nombre" name="turno"></div>'
            $(".cnt-formulario").append(html)

        });
        $("#guardar_crear_turno").click(function(event) {
            /* Act on the event */
            event.preventDefault();
            var arreglo_turno = new Array()
            var contador_listado = $(".listado_idioma tr").length
            var url_turno_crear = '{% url "programacion:api_turno_agregar" %}'
            $(".turno_nombre").each(function(index, el) {
                arreglo_turno.push($(this).val())
            });

            ajax_crear_turno(arreglo_turno, url_turno_crear, contador_listado)
        });
        $("body").on('click', '.modificar_turno', function(event) {
            /* Act on the event */
            event.preventDefault()
            var padre_fila = $(this).closest('.row-fila')
            var texto = padre_fila.find('.nombre_turno h5').text()
            padre_fila.find('.input_modificar').val(texto);
            padre_fila.find('.input_modificar').attr('type', 'text');
            padre_fila.find('.nombre_turno h5').text("")
            padre_fila.find('.actualizar_turno').removeClass('guardar_none').addClass('guardar_block')
            padre_fila.find('.modificar_turno').addClass('guardar_none')
        });
        $("body").on('click', '.actualizar_turno', function(event) {
            event.preventDefault();
            console.log("entro")
            var padre_fila = $(this).closest('.row-fila')
            var pk = padre_fila.find('.input_modificar').attr('data-pk');
            var texto = padre_fila.find('.input_modificar').val()
            url_idioma_actualizar = '{% url "programacion:api_turno_actualizar" %}'
            /* Act on the event */
            ajax_actualizar_turno(padre_fila, texto, pk, url_idioma_actualizar)
        });
    });
</script>
{% endblock javascript %}